In [57]:
import numpy as np
from numpy import pi
from numpy import newaxis

In [19]:
# Task 1. Создание матрицы
a = np.arange(15).reshape(3, 5)
print(a)

print(f"\nКоличество осей матрицы: {a.ndim}")
print(f"Размерность: {a.shape}")
print(f"Количество элементов: {a.size}")
print(f"Тип данных: {a.dtype}")
print(f"Размер элемента в матрице: {a.itemsize}\n")

b = np.array([6, 7, 8])
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Количество осей матрицы: 2
Размерность: (3, 5)
Количество элементов: 15
Тип данных: int32
Размер элемента в матрице: 4

[6 7 8]


In [38]:
# Task 2. Создание массива
c = np.array([[1, 2], [3, 4]], dtype = complex)
print(f"c = {c}\n")

a = np.zeros((3, 4))
b = np.zeros((3, 4), dtype= np.int16)
print(f"a = {a}\n")
print(f"b = {b}\n")

c = np.arange(10, 30, 5)
print(f"c = {c}")
d = np.arange(0, 2,0.3)
print(f"{d}\n")

e = np.linspace(0, 2, 9)
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
print(e, x, f)

c = [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]

a = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

b = [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

c = [10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ] [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37

In [ ]:
# Создание массивов

# array(obj, dtype = None, copy = True, order = 'K', subok = False, ndmin = 0)
# Создает массив из любого объекта, который может быть преобразован в массив.
# Например, из списка, кортежа или другого массива.
# dtype: тип элементов массива
# copy: копировать ли данные или использовать ссылку
# order: порядок элементов в памяти
# subok: создать подкласс ndarray, если obj является подклассом ndarray
# ndmin: минимальная размерность массива
arr1 = np.array([1, 2, 3])  # Одномерный массив
arr2 = np.array([[1, 2], [3, 4]])  # Двумерный массив

# zeros(shape, dtype = float, order = 'C')
# Создает массив, заполненный нулями.
# shape: форма массива (кортеж из размеров)
# dtype: тип элементов
# order: порядок элементов в памяти
zeros_arr = np.zeros((3, 3))  # Массив 3x3, заполненный нулями

# zeros_like(a, dtype = None, order = 'K', subok = True, shape = None)
# Создает массив нулей такой же формы и типа, как массив a.
zeros_like_arr = np.zeros_like(arr1)

# ones(shape, dtype = float, order = 'C')
# Создает массив, заполненный единицами.
# Аргументы аналогичны zeros()
ones_arr = np.ones((2, 2))

# ones_like(a, dtype = None, order = 'K', subok = True, shape = None)
# Создает массив единиц такой же формы и типа, как массив a.
ones_like_arr = np.ones_like(arr2)

# empty(shape, dtype = float, order = 'C')
# Создает массив, не инициализируя его значения.
# Содержимое будет произвольным, так как память не очищается.
# Используйте с осторожностью!
empty_arr = np.empty((2, 2))

# empty_like(a, dtype = None, order = 'K', subok = True, shape=None)
# Создает пустой массив такой же формы и типа, как массив a.
empty_like_arr = np.empty_like(arr1)

# Создание массивов с заданным диапазоном значений

# arange([start, ]stop, [step, ]dtype=None)
# Создает массив с равномерно распределенными значениями в заданном диапазоне.
# start: начальное значение (включительно, по умолчанию 0)
# stop: конечное значение (исключительно)
# step: шаг (по умолчанию 1)
arange_arr = np.arange(10)  # Массив от 0 до 9
arange_step_arr = np.arange(0, 1, 0.1)  # Массив от 0 до 1 с шагом 0.1

# linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)
# Создает массив с равномерно распределенными значениями в заданном диапазоне.
# start: начальное значение
# stop: конечное значение
# num: количество элементов в массиве
# endpoint: включить ли конечное значение
linspace_arr = np.linspace(0, 1, 10)  # 10 точек от 0 до 1

# Случайные числа

# random.rand(d0, d1, ..., dn)
# Создает массив случайных чисел в диапазоне [0, 1).
rand_arr = np.random.rand(3, 3)

# random.randn(d0, d1, ..., dn)
# Создает массив случайных чисел из стандартного нормального распределения.
randn_arr = np.random.randn(2, 2)

# Создание массивов из функций

# fromfunction(function, shape, **kwargs)
# Создает массив, вычисляя значения элементов по заданной функции.
def my_function(i, j):
    return i + j
fromfunction_arr = np.fromfunction(my_function, (3, 3))

# fromfile(file, dtype = float, count =- 1, sep = '', offset = 0)
# Создает массив из данных, прочитанных из файла.
# file: имя файла или открытый файл
# dtype: тип элементов
# count: количество элементов для чтения
# sep: разделитель между элементами (если файл содержит текстовые данные)
fromfile_arr = np.fromfile('data.txt', sep = ',')

In [32]:
# Task 3. Основные операции

a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
d = b ** 2
f = 10*np.sin(a)
k = a < 35

print(f"a = {a}")
print(f"b = {b}")
print(f"c = a - b = {c}")
print(f"d = b ** 2 = {d}")
print(f"f = {f}")
print(f"k = {k}")

a = [20 30 40 50]
b = [0 1 2 3]
c = a - b = [20 29 38 47]
d = b ** 2 = [0 1 4 9]
f = [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
k = [ True  True False False]


In [37]:
b = np.arange(12).reshape(3, 4)
print(f"b = {b}\n")
s1 = b.sum(axis = 0)
print(f"s1 = {s1}\n")
s2 = b.sum(axis = 1)
print(f"s2 = {s2}\n")

max_element = np.max(b)
print("Максимальный элемент всей матрицы:", max_element)

max_rows = np.max(b, axis=1)
print("Максимальные элементы по строкам:", max_rows)

max_cols = np.max(b, axis=0)
print("Максимальные элементы по столбцам:", max_cols)

b = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

s1 = [12 15 18 21]

s2 = [ 6 22 38]

Максимальный элемент всей матрицы: 11
Максимальные элементы по строкам: [ 3  7 11]
Максимальные элементы по столбцам: [ 8  9 10 11]


In [44]:
# Task 4. Индексы

# Создаем массив из кубов чисел от 0 до 9
a = np.arange(10) ** 3
print(f"{a}\n")
# Доступ к элементу с индексом 2 (третий элемент)
print(f"{a[2]}")
# Срез массива: элементы с индексами от 2 до 4 (не включая 5)
print(f"{a[2:5]}")
# Изменение элементов с индексами от 0 до 5 (не включая 6) с шагом 2 на -1000
a[:6:2] = -1000
print(f"{a}")
# Разворот массива
print(f"{a[::- 1]}\n")
# Итерация по элементам массива и вычисление кубического корня
for i in a:
    print(i ** (1/3))

[  0   1   8  27  64 125 216 343 512 729]

8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\dapol\AppData\Local\Temp\ipykernel_21284\995346620.py:17: RuntimeWarning: invalid value encountered in power
  print(i ** (1/3))


In [46]:
# Пример индексации многомерного массива

# Создаем массив из 20 элементов с плавающей точкой (от 0 до 19)
# и преобразуем его в матрицу 5х4
b = np.arange(20, dtype = float).reshape(5, 4)

# Выводим элемент на пересечении 3-й строки и 4-го столбца (индексация начинается с 0)
print(b[2, 3])

# Выводим весь второй столбец (индекс 1)
# Диапазон по строкам 0:5 означает, что мы берем все строки
print(b[0:5, 1])

# Эквивалентно предыдущей строке: выводим весь второй столбец
# : означает, что мы берем все элементы по указанному измерению
print(b[:, 1])

# Выводим подматрицу, состоящую из второй и третьей строк и всех столбцов
print(b[1:3, :])

# Выводим последнюю строку матрицы. Эквивалентно b[-1, :]
print(b[-1]) # equals b[-1, :]

11.0
[ 1.  5.  9. 13. 17.]
[ 1.  5.  9. 13. 17.]
[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[16. 17. 18. 19.]


In [50]:
c = np.array([[[ 0, 1,2],[10,12, 13]],[[100, 101, 102],[110, 112,113]]])
print(c)
print(f"{c[1, ... ]}\n") # equals c[1, :, :] or c[1]
print(f"{c[ ... , 2]}\n") # equals c[:, :, 2]

for element in b.flat:
    print(element)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
[[100 101 102]
 [110 112 113]]

[[  2  13]
 [102 113]]

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0


In [54]:
# Task 4. Преобразование формы матрицы

a = np.floor(10*np.random.random((3, 4)))
print(a)
print(f"{a.shape}\n")

print(a.ravel())
print(a.reshape(6, 2))
print(a.T)
print(a.T.shape)
print(f"{a.shape}\n")

a = np.floor(10*np.random.random((3, 4)))
print(a)
a.resize((2, 6))
print(a)
a.reshape(3, -1)
print(a)
b = a.reshape(3, -1)
print(b)

[[6. 9. 4. 2.]
 [8. 2. 6. 8.]
 [3. 6. 0. 5.]]
(3, 4)

[6. 9. 4. 2. 8. 2. 6. 8. 3. 6. 0. 5.]
[[6. 9.]
 [4. 2.]
 [8. 2.]
 [6. 8.]
 [3. 6.]
 [0. 5.]]
[[6. 8. 3.]
 [9. 2. 6.]
 [4. 6. 0.]
 [2. 8. 5.]]
(4, 3)
(3, 4)

[[3. 8. 4. 7.]
 [3. 2. 0. 9.]
 [0. 3. 9. 2.]]
[[3. 8. 4. 7. 3. 2.]
 [0. 9. 0. 3. 9. 2.]]
[[3. 8. 4. 7. 3. 2.]
 [0. 9. 0. 3. 9. 2.]]
[[3. 8. 4. 7.]
 [3. 2. 0. 9.]
 [0. 3. 9. 2.]]


In [56]:
# Task 5. Объединение и разбиение массива

a = np.floor(10*np.random.random((2, 2)))
b = np.floor(10*np.random.random((2,2)))
V = np.vstack((a, b))
h = np.hstack((a, b))
print(f"{V}\n")
print(h)

[[6. 6.]
 [6. 3.]
 [4. 6.]
 [7. 7.]]

[[6. 6. 4. 6.]
 [6. 3. 7. 7.]]


In [60]:
# Task 6. Копирование массива

d = np.column_stack((a, b))
print(f"{d, 'column_stack'}\n")
a = np.array([4., 2.])
b = np.array([3., 8.])
d = np.column_stack((a, b))
print(f"{d}\n")
d = np.hstack((a, b))
print(f"{a[:, newaxis], 'newaxis'}\n")
print(f"{np.column_stack((a[:,newaxis], b[:, newaxis]))}\n")
print(f"{np.hstack((a[:, newaxis], b[:, newaxis]))}\n")

(array([[4., 3.],
       [2., 8.]]), 'column_stack')

[[4. 3.]
 [2. 8.]]

(array([[4.],
       [2.]]), 'newaxis')

[[4. 3.]
 [2. 8.]]

[[4. 3.]
 [2. 8.]]



In [63]:
a = np.arange(12)
b = a
print(b is a)
print(b.shape)
print(a.shape)
def f(x):
    print(id(x))
print(f"{id(a)}\n")

d = a.copy()
print(d is a)
print(d.base is a)
d[0] = 9999
print(a)

True
(12,)
(12,)
2448000235632

False
False
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [64]:
# Task 7. Индексирование через массивы

a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
print(a[i])
j = np.array([[3, 4], [9, 7]])
print(f"{[j]}\n")

# Логические значения для индексирования
a = np.arange(12).reshape(3, 4)
b = a>4
print(b)
print(a[b])

[ 1  1  9 64 25]
[array([[3, 4],
       [9, 7]])]

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
