In [58]:
import numpy as np

In [59]:
# Вариант 5. Задание 1

n = 10
A = np.random.uniform(-20, 20, n)
print(f"A: {A.round(5)}\n")

# 1. Максимальный элемент массива
max_element = np.max(A)
print(f"Максимальный элемент массива: {max_element.round(5)}")

A: [ 19.64563   7.67632 -17.85706  -3.81852  -5.49417 -17.5732  -19.82834
  -0.19146 -15.60233  -2.57111]

Максимальный элемент массива: 19.64563


In [60]:
# 2. Сумма элементов массива до последнего положительного элемента
last_positive_index = np.where(A > 0)[0][-1] if np.any(A > 0) else -1
sum_before_last_positive = np.sum(A[:last_positive_index]) if last_positive_index != -1 else 0
print(f"Сумма элементов до последнего положительного элемента: {sum_before_last_positive.round(5)}")

Сумма элементов до последнего положительного элемента: 19.64563


In [61]:
# 3. Сжатие массива, удаление элементов с модулем в интервале [a, b]
a, b = 0, 5
mask = (np.abs(A) < a) | (np.abs(A) > b)
A_compressed = A[mask]

# Заполнение оставшихся мест нулями
compressed_array = np.concatenate([A_compressed, np.zeros(n - len(A_compressed))])
print(f"Сжатый массив: {A_compressed.round(5)}")

Сжатый массив: [ 19.64563   7.67632 -17.85706  -5.49417 -17.5732  -19.82834 -15.60233]


In [63]:
# Задание 2.

m, n = 5, 4

matrix = np.random.randint(-10, 10, (m, n))
print(f"Matrix: \n{matrix.round(3)}\n")

zero_columns_count = np.sum(np.any(matrix == 0, axis = 0))
print(f"Количество столбцов с хотя бы одним нулевым элементом: {zero_columns_count}")

Matrix: 
[[  4  -2  -7  -2]
 [ -8   8  -6   6]
 [  7   8 -10   0]
 [  3   4  -4   0]
 [  4   9  -1   8]]

Количество столбцов с хотя бы одним нулевым элементом: 1
